#!/usr/bin/env node
/**
 * Bake package.json name/version into src/version.ts before `tsc`.
 * Keeps session client_version and McpServer metadata aligned with the package.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'));
const name = typeof pkg.name === 'string' ? pkg.name : 'r3ngine-mcp';
const version = typeof pkg.version === 'string' ? pkg.version : '0.0.0';
const out = path.join(root, 'src', 'version.ts');
const body = `/** Generated by scripts/sync-version.mjs from package.json — do not edit by hand. */
export const PACKAGE_NAME = ${JSON.stringify(name)} as const;
export const PACKAGE_VERSION = ${JSON.stringify(version)} as const;
`;
writeFileSync(out, body);
